#include <YSI_Coding\y_hooks>

new tmpobjid;
new object_world = -1, object_int = -1;

#include <..\..\sources\objects\airport.inc>
#include <..\..\sources\objects\alcatraz.inc>
#include <..\..\sources\objects\autoshow.inc>
#include <..\..\sources\objects\at-t_arena.inc>
#include <..\..\sources\objects\horizon_apartments.inc>
#include <..\..\sources\objects\horizon_mobile.inc>
#include <..\..\sources\objects\bank.inc>
#include <..\..\sources\objects\bus_interior.inc>
#include <..\..\sources\objects\bus_station.inc>
#include <..\..\sources\objects\silicon_valley.inc>
#include <..\..\sources\objects\sf_building.inc>
#include <..\..\sources\objects\government.inc>
#include <..\..\sources\objects\dmv.inc>
#include <..\..\sources\objects\hospital_interior.inc>
#include <..\..\sources\objects\pd_exterior.inc>
#include <..\..\sources\objects\pd_interior.inc>
#include <..\..\sources\objects\business_cafe.inc>
#include <..\..\sources\objects\business_clothing.inc>
#include <..\..\sources\objects\business_bar.inc>
#include <..\..\sources\objects\chilliad_road.inc>
#include <..\..\sources\objects\national_park.inc>

