#include <YSI_Coding\y_hooks>


#define COLOR_MAIN 			0xff5c77FF
#define MAIN_COLOR			"{ff5c77}"

#define COLOR_GREY          0xAFAFAFAA
#define GREY_COLOR			"{AFAFAF}"

#define COLOR_ERROR         0xAFAFAFAA
#define ERROR_COLOR			"{AFAFAF}"

#define COLOR_FLAME			0xC01528FF
#define FLAME_COLOR  		"{C01528}"

#define COLOR_PURPLE		0xC2A2DAFF
#define PURPLE_COLOR		"{C2A2DA}"

#define COLOR_YELLOW        0xFFFF00AA
#define YELLOW_COLOR        "{FFFF00}"

#define COLOR_GREEN 		0x46BD38FF
#define GREEN_COLOR         "{46BD38}"

#define COLOR_PINK 			0xE75480FF
#define PINK_COLOR          "{E75480}"

#define COLOR_RED 			0xE05A5AFF
#define RED_COLOR           "{E05A5A}"

#define COLOR_DARKRED 		0xAA3333AA
#define DARKRED_COLOR	    "{AA3333}"

#define COLOR_TAXI 			0xFFCC00FF
#define TAXI_COLOR          "{FFCC00}"

#define COLOR_ORANGE        0xFF9945FF
#define ORANGE_COLOR		"{FF9945}"

#define COLOR_WHITE 		"{FFFFFF}"