// @ts-check
// Сайдбар генерируется автоматически из структуры папок docs/.
// Порядок и названия категорий задаются через _category_.json и sidebar_position во frontmatter.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
